# Istio設定ファイル (Node Taint対応版)
# 
# 重要な発見事項:
# - AKSのシステムノードプール: CriticalAddonsOnly=true:NoSchedule
# - AKSのユーザーノードプール: workload=user:NoSchedule  
# - Istio PodsがPending状態になるのを防ぐため、適切なtolerationが必須
# - nodeSelector: agentpool=user でユーザーノードプールに配置
#
# 適用方法:
# istioctl install --set values.pilot.env.EXTERNAL_ISTIOD=false -f istio-install-config-fixed.yaml
#
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
spec:
  values:
    defaultRevision: default
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
    pilot:
      traceSampling: 100.0
  components:
    pilot:
      k8s:
        # AKS Node Taint対応のtoleration設定
        tolerations:
          - key: "workload"
            operator: "Equal"
            value: "user"
            effect: "NoSchedule"
          - key: "CriticalAddonsOnly"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
        # ユーザーノードプールに配置
        nodeSelector:
          agentpool: user
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          # AKS Node Taint対応のtoleration設定
          tolerations:
            - key: "workload"
              operator: "Equal"
              value: "user"
              effect: "NoSchedule"
            - key: "CriticalAddonsOnly"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
          # ユーザーノードプールに配置
          nodeSelector:
            agentpool: user
          service:
            type: LoadBalancer
            # ゼロトラスト要件: 内部ロードバランサー必須
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "snet-aks"
