apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info
  namespace: default
  labels:
    app: pod-info
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-info
      version: v1
  template:
    metadata:
      labels:
        app: pod-info
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "user"
        effect: "NoSchedule"
      containers:
      - name: pod-info
        image: gcr.io/google-samples/node-hello:1.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pod-info
  namespace: default
  labels:
    app: pod-info
spec:
  selector:
    app: pod-info
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
